[package]
edition = "2021"
name = "<seaography-package-name>"
version = "0.3.0"

[dependencies]
actix-web = { version = "4.3.1", default-features = false, features = ["macros"] }
async-graphql-actix-web = { version = "5.0.6" }
async-graphql = { version = "5.0.6", features = ["decimal", "chrono", "dataloader", "dynamic-schema"] }
async-trait = { version = "0.1.64" }
dotenv = "0.15.0"
sea-orm = { version = "0.12.0-rc.2", features = ["<seaography-sql-library>", "runtime-async-std-native-tls", "seaography"] }
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.16" }
lazy_static = { version = "1.4.0" }

[dependencies.seaography]
version = "<seaography-version>" # seaography version
features = ["with-decimal", "with-chrono"]

[dev-dependencies]
serde_json = { version = "1.0.82" }

[workspace]
members = []