[package]
edition = "2021"
name = "<seaography-package-name>"
version = "0.1.0"

[dependencies]
actix-web = { version = "4.0.1", default-features = false, features = ["macros"] }
async-graphql = { version = "5", features = ["decimal", "chrono", "dataloader"] }
async-graphql-actix-web = { version = "5" }
async-trait = { version = "0.1.53" }
dotenv = "0.15.0"
sea-orm = { version = "0.11", features = ["<seaography-sql-library>", "runtime-async-std-native-tls"] }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.34" }
tracing-subscriber = { version = "0.3.11" }
lazy_static = { version = "1.4.0" }

[dependencies.seaography]
version = "<seaography-version>" # seaography version
features = ["with-decimal", "with-chrono"]

[dev-dependencies]
serde_json = { version = "1.0.82" }

[workspace]
members = []