[package]
name = "seaography_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.21"
url = "2.2.2"
proc-macro2 = "1.0.43"
syn = { version = "1.0.99", features = ["full"] }
heck = "0.4.0"
itertools = "0.10.3"
sea-orm-codegen = { version = "0.9.2"}
seaography_discoverer = { path = "../discoverer" }