[package]
name = "seaography_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.18"
url = "2.2.2"
proc-macro2 = "1.0.37"
syn = { version = "1.0.99", features = ["full"] }
heck = "0.4.0"
toml = "0.5.9"
serde = { version = "1.0.137", features = ["derive"] }
clap = { version = "3.2.6", features = ["derive"] }
itertools = "0.10.3"
sea-orm-codegen = { version = "^0.9.1"}
seaography_discoverer = { path = "../discoverer" }