[package]
name = "seaography-generator"
version = "0.1.0"
edition = "2021"
rust-version = "1.60"
authors = ["Panagiotis Karatakis <panagiotiskaratakis@gmail.com>"]
description = "ðŸ§­ A GraphQL framework and code generator for SeaORM"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/seaography"
repository = "https://github.com/SeaQL/seaography"
keywords = ["async", "graphql", "mysql", "postgres", "sqlite"]
categories = ["database"]

[dependencies]
quote = "1.0.21"
proc-macro2 = "1.0.43"
syn = { version = "1.0.99", features = ["full"] }
heck = "0.4.0"
itertools = "0.10.3"
sea-orm-codegen = { version = "0.9.2"}
sea-query = { version = "0.26.3", default-features = false }