[package]
edition = '2021'
name = 'seaography-example-sqlite'
version = '0.1.0'

[dependencies]
async-graphql = { version = "4.0.10", features = ["decimal", "chrono", "dataloader"] }
async-graphql-poem = { version = "4.0.10" }
async-trait = { version = "0.1.53" }
heck = { version = "0.4.0" }
itertools = { version = "0.10.3" }
poem = { version = "1.3.29" }
sea-orm = { version = "0.7.0", features = ["sqlx-sqlite", "runtime-async-std-native-tls"] }
seaography = { path = "../../", features = [ "with-decimal", "with-chrono" ] } # TODO before production place version here
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.34" }
tracing-subscriber = { version = "0.3.11" }
dotenv = "0.15.0"

[dev-dependencies]
serde_json = { version = '1.0.82' }

[workspace]
members = []